# Generated by Django 2.0.6 on 2019-01-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'managed': False},
        ),
    ]
