# Generated by Django 2.2 on 2018-12-27 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'pasajes_pasajero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('documento', models.IntegerField(unique=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('cuit', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('documento', models.IntegerField(unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('id_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Agente', verbose_name='Agente')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('via', models.CharField(max_length=200)),
                ('fecha_viaje', models.DateField()),
                ('fecha_emision', models.DateTimeField(default=datetime.datetime(2018, 12, 27, 10, 34, 36, 583585))),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('id_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Agente', verbose_name='Agente')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Empresa', verbose_name='Empresa')),
                ('id_familiar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pasajes.Familiar', verbose_name='Familiar')),
            ],
        ),
        migrations.AddField(
            model_name='familiar',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Localidad', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Localidad', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='agente',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Localidad', verbose_name='Localidad'),
        ),
    ]
