# Generated by Django 2.2 on 2019-01-03 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cuit',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='pasaje',
            name='fecha_emision',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 11, 15, 8, 215818)),
        ),
    ]
