# Generated by Django 2.2 on 2018-12-27 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0013_auto_20181217_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'pasajes_pasajero',
            },
        ),
        migrations.AddField(
            model_name='pasaje',
            name='id_familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pasajes.Familiar', verbose_name='Familiar'),
        ),
        migrations.AlterField(
            model_name='pasaje',
            name='fecha_emision',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 10, 30, 41, 551737)),
        ),
    ]
